const tasks=window.ledgerTasks,escape=window.ledgerHelpers.escape;
const board=document.querySelector("#task-list"),search=document.querySelector("#search"),params=new URLSearchParams(location.search);
let lens=["all","attention","waiting"].includes(params.get("lens"))?params.get("lens"):"all";
const columns=[
{id:"not-started",label:"Not Started",states:["Queued","Blocked","Canceled"]},
{id:"in-progress",label:"In Progress",states:["Running","Waiting externally"]},
{id:"completed",label:"Completed",states:["Completed"]}
];
const stateNote={Queued:"Not begun",Blocked:"Cannot begin",Canceled:"Stopped · not completed",Running:"Active","Waiting externally":"Underway · waiting",Completed:"Verified done"};
function matches(task){const q=search.value.trim().toLowerCase();const lensMatch=lens==="all"||(lens==="attention"&&task.lens==="attention")||(lens==="waiting"&&task.lens==="waiting");return lensMatch&&(!q||[task.title,task.state,task.qualifier,task.next].join(" ").toLowerCase().includes(q));}
function card(task){const alert=task.lens==="attention"?" attention":"",open=params.get("detail")===task.id?" open":"";return `<li class="action-card"><div class="card-top"><span class="state-label${alert}">${escape(task.state)}</span><span class="mapping-note">${escape(stateNote[task.state])}</span></div><h3>${escape(task.title)}</h3><p class="card-status${alert}">${escape(task.qualifier)}</p><p class="card-next">${escape(task.next)}</p><p class="card-time">${escape(task.due)}</p><details class="card-disclosure"${open}><summary>Details<span class="sr-only"> for ${escape(task.title)}</span></summary><p class="card-update">${escape(task.evidence)}</p><p class="card-scope">Evidence observed ${escape(task.observedAt)} · view updated 14:32 UTC</p><ol class="history">${task.chronology.map(e=>`<li><time>${escape(e[0])}</time><div>${escape(e[1])}</div></li>`).join("")}</ol></details></li>`;}
function completedGroups(items){const sorted=[...items].sort((a,b)=>{if(a.completedAt&&b.completedAt)return b.completedAt.localeCompare(a.completedAt)||a.id.localeCompare(b.id);if(a.completedAt)return -1;if(b.completedAt)return 1;return a.id.localeCompare(b.id);});const groups=[];for(const task of sorted){const label=task.completedDay||"Completion time unavailable";let group=groups.find(g=>g.label===label);if(!group){group={label,items:[]};groups.push(group);}group.items.push(task);}return groups.map(group=>`<section class="completion-group" aria-label="${escape(group.label)}"><h3>${escape(group.label)}</h3><ol class="column-cards">${group.items.map(task=>card(task)).join("")}</ol></section>`).join("");}
function render(){const visible=tasks.filter(matches);board.innerHTML=columns.map(column=>{const members=visible.filter(task=>column.states.includes(task.state));const body=column.id==="completed"?completedGroups(members):`<ol class="column-cards">${members.map(task=>card(task)).join("")}</ol>`;return `<section class="board-column" id="column-${column.id}" aria-labelledby="heading-${column.id}"><div class="column-heading"><div><h2 id="heading-${column.id}" tabindex="-1">${column.label}</h2>${column.id==="completed"?'<p>Newest verified completion first</p>':""}</div><span aria-label="${members.length} tasks">${members.length}</span></div><div class="column-scroll" tabindex="0" aria-label="${column.label} items, scrollable">${body}${members.length?"":'<p class="column-empty">No tasks in this view</p>'}</div></section>`;}).join("");document.querySelector("#empty").hidden=visible.length>0;document.querySelector("#active-scope").textContent=`${visible.length} of ${tasks.length} tasks · three presentation columns`;document.querySelectorAll("[data-lens]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.lens===lens)));}
document.querySelectorAll("[data-lens]").forEach(b=>b.addEventListener("click",()=>{lens=b.dataset.lens;render();}));search.addEventListener("input",render);document.querySelector("#reset").addEventListener("click",()=>{lens="all";search.value="";render();search.focus();});document.querySelector("#state-jump").addEventListener("change",event=>{const target=document.querySelector("#heading-"+event.target.value);if(target){target.scrollIntoView({block:"start"});target.focus({preventScroll:true});}});render();
