window.ledgerTasks = [
{id:"task_synth_104",state:"Running",qualifier:"Expired claim",title:"Verify callback delivery",next:"Check current state before any replacement attempt.",due:"Recovery review overdue",observedAt:"14:00 UTC",evidence:"Synthetic callback receipt recorded; no later task fetch is recorded.",lens:"attention",completedAt:null,chronology:[["14:06 UTC","Claim expired"],["14:01 UTC","Callback receipt recorded"]]},
{id:"task_synth_103",state:"Blocked",qualifier:"Owner decision",title:"Choose retention defaults",next:"Choose the retention periods in chat.",due:"No deadline set",observedAt:"13:42 UTC",evidence:"Owner approval is not recorded.",lens:"attention",completedAt:null,chronology:[["13:42 UTC","Blocked"],["13:40 UTC","Proposal recorded"]]},
{id:"task_synth_101",state:"Waiting externally",qualifier:"Missed check · 18m",title:"Confirm scheduled status check",next:"Run the overdue read-only source check.",due:"Check was due 14:14 UTC",observedAt:"13:43 UTC",evidence:"Synthetic dependency remained pending at the last observation.",lens:"attention",completedAt:null,chronology:[["14:14 UTC","Check became overdue"],["13:44 UTC","Waiting externally"]]},
{id:"task_synth_107",state:"Canceled",qualifier:"External outcome uncertain",title:"Reconcile status publication",next:"Check the original result without restarting work.",due:"Canceled 14:22 UTC",observedAt:"14:21 UTC",evidence:"The request timed out after possible acceptance; cancellation does not establish rollback.",lens:"attention",completedAt:null,chronology:[["14:22 UTC","Canceled"],["14:21 UTC","Outcome uncertain"]]},
{id:"task_synth_105",state:"Queued",qualifier:"Eligible",title:"Prepare reconnect test",next:"Start when the approved environment is available.",due:"Eligible since 14:25 UTC",observedAt:"14:25 UTC",evidence:"Synthetic prerequisite data is ready.",lens:"waiting",completedAt:null,chronology:[["14:25 UTC","Became eligible"],["14:12 UTC","Queued"]]},
{id:"task_synth_108",state:"Queued",qualifier:"Scheduled",title:"Review recovery copy",next:"Begin after the scheduled review window opens.",due:"Eligible Oct 9 · 09:00",observedAt:"14:26 UTC",evidence:"The synthetic review window is recorded.",lens:"waiting",completedAt:null,chronology:[["14:26 UTC","Queued"]]},
{id:"task_synth_109",state:"Blocked",qualifier:"Access needed",title:"Confirm test account scope",next:"Resolve the narrow synthetic account scope in chat.",due:"Waiting for owner",observedAt:"14:27 UTC",evidence:"No scope approval is recorded.",lens:"attention",completedAt:null,chronology:[["14:27 UTC","Blocked"]]},
{id:"task_synth_110",state:"Running",qualifier:"In progress",title:"Compare projection snapshots",next:"Finish the deterministic comparison.",due:"Next check 14:45 UTC",observedAt:"14:28 UTC",evidence:"Two synthetic snapshots are available for comparison.",lens:"progress",completedAt:null,chronology:[["14:28 UTC","Comparison started"]]},
{id:"task_synth_111",state:"Waiting externally",qualifier:"Dependency pending",title:"Wait for renderer receipt",next:"Check the synthetic receiver at 15:00 UTC.",due:"Next check 15:00 UTC",observedAt:"14:29 UTC",evidence:"The receiver is still pending.",lens:"waiting",completedAt:null,chronology:[["14:29 UTC","Waiting externally"]]},
{id:"task_synth_099",state:"Completed",qualifier:"Evidence verified",title:"Validate bounded UI payload",next:"No further action.",due:"Completed 13:18 UTC",observedAt:"13:17 UTC",evidence:"Fixture passed documented presentation bounds.",lens:"complete",completedAt:"2026-10-08T13:18:00Z",completedDay:"Today · Oct 8",completedTime:"09:18",chronology:[["13:18 UTC","Completed"]]},
{id:"task_synth_098",state:"Completed",qualifier:"Evidence verified",title:"Capture mobile overflow check",next:"No further action.",due:"Completed 11:42 UTC",observedAt:"11:41 UTC",evidence:"The 390 px viewport had no horizontal overflow.",lens:"complete",completedAt:"2026-10-08T11:42:00Z",completedDay:"Today · Oct 8",completedTime:"07:42",chronology:[["11:42 UTC","Completed"]]},
{id:"task_synth_097",state:"Completed",qualifier:"Evidence verified",title:"Confirm keyboard disclosure",next:"No further action.",due:"Completed Oct 7 · 20:06 UTC",observedAt:"20:05 UTC",evidence:"Native disclosure opened with Enter and retained focus.",lens:"complete",completedAt:"2026-10-07T20:06:00Z",completedDay:"Yesterday · Oct 7",completedTime:"16:06",chronology:[["20:06 UTC","Completed"]]},
{id:"task_synth_096",state:"Completed",qualifier:"Evidence verified",title:"Review reduced transparency",next:"No further action.",due:"Completed Oct 7 · 16:30 UTC",observedAt:"16:29 UTC",evidence:"Cards rendered with solid-white fallback surfaces.",lens:"complete",completedAt:"2026-10-07T16:30:00Z",completedDay:"Yesterday · Oct 7",completedTime:"12:30",chronology:[["16:30 UTC","Completed"]]},
{id:"task_synth_095",state:"Completed",qualifier:"Completion time unavailable",title:"Archive earlier design notes",next:"No further action.",due:"Completion time unavailable",observedAt:"Time unavailable",evidence:"Completion is verified, but the source timestamp is missing and is not inferred.",lens:"complete",completedAt:null,completedDay:"Completion time unavailable",completedTime:"—",chronology:[["Time unavailable","Completed; timestamp missing"]]}
];
window.ledgerHelpers={escape(value){return String(value).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}};
